## Documentation: http://docs.travis-ci.com/user/languages/julia/

branches:
  only:
    - master
    - staging
    - trying
    - /^release\/.*$/ # release branches
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

env:
  global:
    - AUTOMERGE_INTEGRATION_TEST_REPO="bcbi-test/automerge-integration-test-repo"
    - JULIA_DEBUG="all"

git:
  depth: 99999999

julia:
  - "1" # "1" expands to the latest 1.y.z release of Julia
  - nightly

language: julia

notifications:
  email: false

os:
  - linux

script: julia --code-coverage --inline=no -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

## Important note:
## If you want to run the integration tests, make sure that you go into the
## Travis settings for your repository, enable the "Limit concurrent jobs"
## option, and set the number of concurrent jobs to one (1).
## For more details, see https://docs.travis-ci.com/user/customizing-the-build/#limiting-concurrent-jobs

jobs:
  include:
    - stage: AutoMerge Integration Tests
      env:
        - AUTOMERGE_RUN_INTEGRATION_TESTS="true"
      julia: "1" # "1" expands to the latest 1.y.z release of Julia
      after_success: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
    - stage: AutoMerge Integration Tests
      env:
        - AUTOMERGE_RUN_INTEGRATION_TESTS="true"
      julia: "nightly"
      after_success: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
