block_labels = [ "DO NOT MERGE" ]

delete_merged_branches = true

status = [
    "Integration/Julia 1/ubuntu-latest/x64",
    "Unit/Julia 1.3/ubuntu-latest/x64",
    "Unit/Julia 1.4/ubuntu-latest/x64",
    "Unit/Julia 1.5/ubuntu-latest/x64",
    "Unit/Julia 1.6/ubuntu-latest/x64",
    "Unit/Julia 1/ubuntu-latest/x64",
    "Unit/Julia nightly/ubuntu-latest/x64",
    "codecov/project/minimum",
    # "codecov/project",
    # "codecov/patch",
]

timeout_sec = 1800
