block_labels = [ "DO NOT MERGE" ]

delete_merged_branches = true

status = [
    # "Integration/Julia 1/ubuntu-latest/x64", # TODO: uncomment this line once Julia 1.6 is released
    "Integration/Julia ^1.6.0-0/ubuntu-latest/x64", # TODO: delete this line once Julia 1.6 is released
    # "Unit/Julia 1.6/ubuntu-latest/x64", # TODO: uncomment this line once Julia 1.6 is released
    # "Unit/Julia 1/ubuntu-latest/x64", # TODO: uncomment this line once Julia 1.6 is released
    "Unit/Julia ^1.6.0-0/ubuntu-latest/x64", # TODO: delete this line once Julia 1.6 is released
    "Unit/Julia nightly/ubuntu-latest/x64",
    "VersionVigilante",
    # "codecov/patch",
    # "codecov/project",
]

timeout_sec = 1800
