coverage:
  status:
    project:
      default:
        target: auto
      minimum:
        target: "70%"
        # target: "75%"
        # target: "80%"
        # target: "85%"
        # target: "90%"
        # target: "95%"
